from pathlib import Path

import pandas as pd

from src.config import APP_TITLE


def generate_html_report(
    df: pd.DataFrame,
    chart_figures: list[tuple[str, str]],
    stats_html: str = "",
) -> str:
    rows = df.head(20).to_html(classes="data-table", index=False)
    chart_sections = ""
    for title, div in chart_figures:
        chart_sections += f"<h2>{title}</h2>\n{div}\n"

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{APP_TITLE} Report</title>
<script src="https://cdn.plot.ly/plotly-2.35.2.min.js"></script>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 1200px; margin: 0 auto; padding: 2rem; color: #333; }}
  h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 0.5rem; }}
  h2 {{ color: #34495e; margin-top: 2rem; }}
  .data-table {{ border-collapse: collapse; width: 100%; margin: 1rem 0; }}
  .data-table th {{ background: #3498db; color: white; padding: 0.5rem; text-align: left; }}
  .data-table td {{ padding: 0.5rem; border-bottom: 1px solid #ddd; }}
  .data-table tr:hover {{ background: #f5f5f5; }}
  .stats {{ background: #f8f9fa; padding: 1rem; border-radius: 4px; margin: 1rem 0; }}
  .footer {{ margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #eee; font-size: 0.85rem; color: #7f8c8d; text-align: center; }}
</style>
</head>
<body>
<h1>{APP_TITLE} Report</h1>
<p>Generated with {len(df)} rows and {len(df.columns)} columns.</p>
{stats_html}
<h2>Data Preview (first 20 rows)</h2>
{rows}
{chart_sections}
<div class="footer">
<p>Generated by Data Storytelling Dashboard &mdash; {__import__("datetime").datetime.now().strftime("%Y-%m-%d %H:%M")}</p>
</div>
</body>
</html>"""
    return html


def export_html_report(
    html: str,
    output_path: str | Path = "dashboard_report.html",
) -> Path:
    path = Path(output_path)
    path.write_text(html, encoding="utf-8")
    return path.absolute()
